packages:
  # all packages in subdirs of packages/ and examples/
  - 'packages/**'
  - 'examples/**'
  - 'server/routerlicious/packages/**'
  - 'server/tinylicious'
  # exclude packages that are inside test/ directories
  # - '!**/test/**'
link-workspace-packages: true
save-workspace-protocol: true
shared-workspace-lockfile: true
