packages:
  - "examples/**"
  - "experimental/**"
  - "packages/**"
  - "server/routerlicious/packages/**"
  - "server/historian/**"
  - "server/gitrest/**"
  - "server/tinylicious/*"
  - "build-tools/packages/**"
