name: Broken Link Check
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  broken_link_check_internal:
    runs-on: ubuntu-latest
    name: Check from broken internal links
    steps:
    - name: Build site artifact
      run: |
        cd $GITHUB_WORKSPACE/docs
        npm ci
        npm run build
        npm start
    - name: Run broken-link-checker
      id: link-report
      uses: tylerbutler/link-checker
      with:
        url: http://localhost:1313
        honorRobotExclusions: true
        ignorePatterns: "https://github.com/*/edit/*,http*://*/docs/apis/*"
        recursiveLinks: true
        additionalArgs: "-ore"
    - name: Report results
      uses: github-actions-up-and-running/pr-comment@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        message: "${{steps.link-report.outputs.result}}"
