name: Broken Link Check
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - "docs/**"

jobs:
  build_site:
    runs-on: ubuntu-latest
    name: Build site
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - uses: actions/setup-node@v2-beta
      with:
        node-version: "12"
    - name: Build site artifact
      run: |
        cd $GITHUB_WORKSPACE/docs
        npm ci
        npm run download
        npm run build
    - name: Upload site artifact
      uses: actions/upload-artifact@v2
      with:
        name: fluidframework-site
        path: docs/public

  broken_link_check_internal:
    runs-on: ubuntu-latest
    name: Check for broken internal links
    steps:
    - uses: actions/setup-node@v2-beta
      with:
        node-version: "12"
    - name: Download site artifact
      uses: actions/download-artifact@v2
      with:
        name: fluidframework-site
        path: $GITHUB_WORKSPACE/docs/public
    - name: Check internal links
      id: linkcheck
      run: |
        npm install pm2 -g
        cd $GITHUB_WORKSPACE/docs
        pm2 start $GITHUB_WORKSPACE/docs/serve.js
        npm run linkcheck
    - name: Success
      if: steps.linkcheck.outcome == "success"
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        header: linkreport
        recreate: true
        message: |
          ### Broken link report

          🔗 No broken links found! ✅

          Your attention to detail is admirable.
    - name: Failure
      if: steps.linkcheck.outcome != "success"
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        header: linkreport
        recreate: true
        message: |
          ### Broken link report

          🔗 Found some broken links! 💔

          Run a link check locally to find them. See
          <https://github.com/microsoft/FluidFramework/wiki/Checking-for-broken-links-in-the-documentation> for more information.
