name: "Commit message validation"

on:
  pull_request:
    branches: [main, commitlint]
    paths: [
      # Commit validation in PRs applies to build-tools only as of now.
      'build-tools/**',
      '.github/workflows/commit-validation.yml'
    ]
    types: [opened, synchronize, edited, ready_for_review]

jobs:
  placeholder-content:
    name: Check that the PR template placeholder content is removed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sitezen/pr-comment-checker@v1.0.1
        with:
          pr_description_should_not_contain: |
            Feel free to remove or alter parts of this template that do not offer value for your specific change
          wrong_pr_description_message: |
            Your PR description contains placeholder content from the PR template. Remove or replace the placeholder
            content. More information at:
            https://github.com/microsoft/FluidFramework/wiki/Commit-message-style#pr-template-content

  conventional-pr-title:
    name: Check that the PR title matches commitlint settings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        name: Install dependencies
        with:
          version: latest
          run_install: |
            - cwd: build-tools
              args: [--ignore-scripts]

      # Lints the PR title according to the settings file in the repo
      - uses: JulienKode/pull-request-name-linter-action@v0.5.0
        name: Lint PR title
        with:
          configuration-path: build-tools/commitlint.config.cjs
